// components/guess-games/capital-guess/capitals.ts
export type Capital = {
  code: string;          // ISO 3166-1 alpha-2 (same as your COUNTRIES list)
  capital: string;       // canonical capital name
  also?: string[];       // optional accepted alternates/synonyms
};

export const CAPITALS: Capital[] = [
  { code: "AF", capital: "Kabul" },
  { code: "AL", capital: "Tirana" },
  { code: "DZ", capital: "Algiers" },
  { code: "AD", capital: "Andorra la Vella", also: ["Andorra-la-Vella"] },
  { code: "AO", capital: "Luanda" },
  { code: "AG", capital: "Saint John's", also: ["St John's", "St. John's"] },
  { code: "AR", capital: "Buenos Aires" },
  { code: "AM", capital: "Yerevan" },
  { code: "AU", capital: "Canberra" },
  { code: "AT", capital: "Vienna" },
  { code: "AZ", capital: "Baku" },
  { code: "BS", capital: "Nassau" },
  { code: "BH", capital: "Manama" },
  { code: "BD", capital: "Dhaka", also: ["Dacca"] },
  { code: "BB", capital: "Bridgetown" },
  { code: "BY", capital: "Minsk" },
  { code: "BE", capital: "Brussels" },
  { code: "BZ", capital: "Belmopan" },
  { code: "BJ", capital: "Porto-Novo", also: ["Cotonou"] },
  { code: "BT", capital: "Thimphu" },
  { code: "BO", capital: "Sucre", also: ["La Paz"] },
  { code: "BA", capital: "Sarajevo" },
  { code: "BW", capital: "Gaborone" },
  { code: "BR", capital: "Brasília", also: ["Brasilia"] },
  { code: "BN", capital: "Bandar Seri Begawan" },
  { code: "BG", capital: "Sofia" },
  { code: "BF", capital: "Ouagadougou" },
  { code: "BI", capital: "Gitega", also: ["Bujumbura"] },
  { code: "CV", capital: "Praia" },
  { code: "KH", capital: "Phnom Penh" },
  { code: "CM", capital: "Yaoundé", also: ["Yaounde"] },
  { code: "CA", capital: "Ottawa" },
  { code: "CF", capital: "Bangui" },
  { code: "TD", capital: "N'Djamena", also: ["Ndjamena"] },
  { code: "CL", capital: "Santiago" },
  { code: "CN", capital: "Beijing", also: ["Peking"] },
  { code: "CO", capital: "Bogotá", also: ["Bogota"] },
  { code: "KM", capital: "Moroni" },
  { code: "CG", capital: "Brazzaville" },
  { code: "CR", capital: "San José", also: ["San Jose"] },
  { code: "CI", capital: "Yamoussoukro", also: ["Abidjan"] },
  { code: "HR", capital: "Zagreb" },
  { code: "CU", capital: "Havana" },
  { code: "CY", capital: "Nicosia" },
  { code: "CZ", capital: "Prague" },
  { code: "CD", capital: "Kinshasa" },
  { code: "DK", capital: "Copenhagen" },
  { code: "DJ", capital: "Djibouti" },
  { code: "DM", capital: "Roseau" },
  { code: "DO", capital: "Santo Domingo" },
  { code: "EC", capital: "Quito" },
  { code: "EG", capital: "Cairo" },
  { code: "SV", capital: "San Salvador" },
  { code: "GQ", capital: "Malabo", also: ["Ciudad de la Paz", "Oyala"] },
  { code: "ER", capital: "Asmara" },
  { code: "EE", capital: "Tallinn" },
  { code: "SZ", capital: "Mbabane", also: ["Lobamba"] },
  { code: "ET", capital: "Addis Ababa" },
  { code: "FJ", capital: "Suva" },
  { code: "FI", capital: "Helsinki" },
  { code: "FR", capital: "Paris" },
  { code: "GA", capital: "Libreville" },
  { code: "GM", capital: "Banjul" },
  { code: "GE", capital: "Tbilisi" },
  { code: "DE", capital: "Berlin" },
  { code: "GH", capital: "Accra" },
  { code: "GR", capital: "Athens" },
  { code: "GD", capital: "St. George's", also: ["Saint George's"] },
  { code: "GT", capital: "Guatemala City" },
  { code: "GN", capital: "Conakry" },
  { code: "GW", capital: "Bissau" },
  { code: "GY", capital: "Georgetown" },
  { code: "HT", capital: "Port-au-Prince" },
  { code: "HN", capital: "Tegucigalpa" },
  { code: "HU", capital: "Budapest" },
  { code: "IS", capital: "Reykjavík", also: ["Reykjavik"] },
  { code: "IN", capital: "New Delhi", also: ["Delhi"] },
  { code: "ID", capital: "Jakarta", also: ["Nusantara"] },
  { code: "IR", capital: "Tehran" },
  { code: "IQ", capital: "Baghdad" },
  { code: "IE", capital: "Dublin" },
  { code: "IL", capital: "Jerusalem", also: ["Tel Aviv"] },
  { code: "IT", capital: "Rome" },
  { code: "JM", capital: "Kingston" },
  { code: "JP", capital: "Tokyo" },
  { code: "JO", capital: "Amman" },
  { code: "KZ", capital: "Astana", also: ["Nur-Sultan", "Nursultan"] },
  { code: "KE", capital: "Nairobi" },
  { code: "KI", capital: "South Tarawa", also: ["Tarawa"] },
  { code: "KW", capital: "Kuwait City" },
  { code: "KG", capital: "Bishkek" },
  { code: "LA", capital: "Vientiane" },
  { code: "LV", capital: "Riga" },
  { code: "LB", capital: "Beirut" },
  { code: "LS", capital: "Maseru" },
  { code: "LR", capital: "Monrovia" },
  { code: "LY", capital: "Tripoli" },
  { code: "LI", capital: "Vaduz" },
  { code: "LT", capital: "Vilnius" },
  { code: "LU", capital: "Luxembourg" },
  { code: "MG", capital: "Antananarivo" },
  { code: "MW", capital: "Lilongwe" },
  { code: "MY", capital: "Kuala Lumpur", also: ["Putrajaya"] },
  { code: "MV", capital: "Malé", also: ["Male"] },
  { code: "ML", capital: "Bamako" },
  { code: "MT", capital: "Valletta" },
  { code: "MH", capital: "Majuro" },
  { code: "MR", capital: "Nouakchott" },
  { code: "MU", capital: "Port Louis" },
  { code: "MX", capital: "Mexico City", also: ["Ciudad de México", "CDMX"] },
  { code: "FM", capital: "Palikir" },
  { code: "MD", capital: "Chișinău", also: ["Chisinau"] },
  { code: "MC", capital: "Monaco" },
  { code: "MN", capital: "Ulaanbaatar", also: ["Ulan Bator", "Ulanbator"] },
  { code: "ME", capital: "Podgorica", also: ["Cetinje"] },
  { code: "MA", capital: "Rabat" },
  { code: "MZ", capital: "Maputo" },
  { code: "MM", capital: "Naypyidaw", also: ["Nay Pyi Taw"] },
  { code: "NA", capital: "Windhoek" },
  { code: "NR", capital: "Yaren" },
  { code: "NP", capital: "Kathmandu" },
  { code: "NL", capital: "Amsterdam", also: ["The Hague", "Hague"] },
  { code: "NZ", capital: "Wellington" },
  { code: "NI", capital: "Managua" },
  { code: "NE", capital: "Niamey" },
  { code: "NG", capital: "Abuja" },
  { code: "KP", capital: "Pyongyang" },
  { code: "MK", capital: "Skopje" },
  { code: "NO", capital: "Oslo" },
  { code: "OM", capital: "Muscat" },
  { code: "PK", capital: "Islamabad" },
  { code: "PW", capital: "Ngerulmud" },
  { code: "PA", capital: "Panama City" },
  { code: "PG", capital: "Port Moresby" },
  { code: "PY", capital: "Asunción", also: ["Asuncion"] },
  { code: "PE", capital: "Lima" },
  { code: "PH", capital: "Manila" },
  { code: "PL", capital: "Warsaw" },
  { code: "PT", capital: "Lisbon" },
  { code: "QA", capital: "Doha" },
  { code: "RO", capital: "Bucharest" },
  { code: "RU", capital: "Moscow" },
  { code: "RW", capital: "Kigali" },
  { code: "KN", capital: "Basseterre" },
  { code: "LC", capital: "Castries" },
  { code: "VC", capital: "Kingstown" },
  { code: "WS", capital: "Apia" },
  { code: "SM", capital: "San Marino" },
  { code: "ST", capital: "São Tomé", also: ["Sao Tome"] },
  { code: "SA", capital: "Riyadh" },
  { code: "SN", capital: "Dakar" },
  { code: "RS", capital: "Belgrade" },
  { code: "SC", capital: "Victoria" },
  { code: "SL", capital: "Freetown" },
  { code: "SG", capital: "Singapore" },
  { code: "SK", capital: "Bratislava" },
  { code: "SI", capital: "Ljubljana" },
  { code: "SB", capital: "Honiara" },
  { code: "SO", capital: "Mogadishu" },
  { code: "ZA", capital: "Pretoria", also: ["Cape Town", "Bloemfontein"] },
  { code: "KR", capital: "Seoul" },
  { code: "SS", capital: "Juba" },
  { code: "ES", capital: "Madrid" },
  { code: "LK", capital: "Sri Jayawardenepura Kotte", also: ["Kotte", "Colombo"] },
  { code: "SD", capital: "Khartoum", also: ["Port Sudan"] },
  { code: "SR", capital: "Paramaribo" },
  { code: "SE", capital: "Stockholm" },
  { code: "CH", capital: "Bern", also: ["Berne"] },
  { code: "SY", capital: "Damascus" },
  { code: "TJ", capital: "Dushanbe" },
  { code: "TZ", capital: "Dodoma", also: ["Dar es Salaam"] },
  { code: "TH", capital: "Bangkok", also: ["Krung Thep"] },
  { code: "TL", capital: "Dili" },
  { code: "TG", capital: "Lomé", also: ["Lome"] },
  { code: "TO", capital: "Nukuʻalofa", also: ["Nuku'alofa", "Nukualofa"] },
  { code: "TT", capital: "Port of Spain" },
  { code: "TN", capital: "Tunis" },
  { code: "TR", capital: "Ankara" },
  { code: "TM", capital: "Ashgabat" },
  { code: "TV", capital: "Funafuti" },
  { code: "UG", capital: "Kampala" },
  { code: "UA", capital: "Kyiv", also: ["Kiev"] },
  { code: "AE", capital: "Abu Dhabi" },
  { code: "GB", capital: "London" },
  { code: "US", capital: "Washington, D.C.", also: ["Washington DC", "Washington"] },
  { code: "UY", capital: "Montevideo" },
  { code: "UZ", capital: "Tashkent" },
  { code: "VU", capital: "Port Vila" },
  { code: "VE", capital: "Caracas" },
  { code: "VN", capital: "Hanoi" },
  { code: "YE", capital: "Sana'a", also: ["Sanaa"] },
  { code: "ZM", capital: "Lusaka" },
  { code: "ZW", capital: "Harare" },
  { code: "VA", capital: "Vatican City", also: ["Holy See"] },
  { code: "PS", capital: "Ramallah", also: ["Jerusalem", "East Jerusalem"] },
];

// — Helpers —
export const CAPITALS_BY_CODE: Record<string, Capital> = Object.fromEntries(
  CAPITALS.map((c) => [c.code, c])
);

export const CAPITAL_SUGGESTIONS: string[] = Array.from(
  new Set(
    CAPITALS.flatMap((c) => [c.capital, ...(c.also ?? [])])
  )
).sort((a, b) => a.localeCompare(b));
