// components/guess-games/language-guess/languages.ts
export type LanguageEntry = {
  code: string; // BCP47-ish language tag (e.g., "ar", "zh-Hans")
  name: string; // Canonical language endonym/exonym
  also?: string[]; // Accepted alternates / synonyms
  dir?: "ltr" | "rtl"; // Text direction
  samples: string[]; // Short, recognizable snippets
};

export const LANGUAGES: LanguageEntry[] = [
  {
    code: "en",
    name: "English",
    also: ["Eng", "EN"],
    samples: [
      "The quick brown fox jumps over the lazy dog.",
      "Please close the door when you leave.",
      "Can you help me find my keys?",
      "We left early to avoid traffic.",
      "I enjoy walking by the river.",
    ],
  },
  {
    code: "de",
    name: "German",
    also: ["Deutsch", "DE"],
    samples: [
      "Ich lerne Deutsch und trinke gern Kaffee.",
      "Das ist nur ein kleines Beispiel.",
      "Wo ist der Bahnhof, bitte?",
      "Heute ist das Wetter wirklich schön.",
      "Ich lerne eine neue Sprache.",
    ],
  },
  {
    code: "fr",
    name: "French",
    also: ["Français", "FR", "Francais"],
    samples: [
      "Je ne sais pas si c'est vrai.",
      "Bonjour, je m'appelle Marie.",
      "Où se trouve la gare ?",
      "Le temps est très beau aujourd'hui.",
      "J'apprends une nouvelle langue.",
    ],
  },
  {
    code: "es",
    name: "Spanish",
    also: ["Español", "Espanol", "Castellano"],
    samples: [
      "¿Dónde está la estación de tren?",
      "Hoy hace mucho calor en la ciudad.",
      "Me gusta leer por la noche.",
      "El tiempo está muy bonito hoy.",
      "Estoy aprendiendo un idioma nuevo.",
    ],
  },
  {
    code: "it",
    name: "Italian",
    also: ["Italiano"],
    samples: [
      "Questo è un semplice esempio di testo.",
      "Mi piace mangiare la pasta la sera.",
      "Dov'è la stazione dei treni?",
      "Oggi il tempo è molto bello.",
      "Sto imparando una nuova lingua.",
    ],
  },
  {
    code: "pt",
    name: "Portuguese",
    also: [
      "Português",
      "Portugues",
      "PT",
      "Portuguese (Portugal)",
      "Portuguese (Brazil)",
      "Brasileiro",
    ],
    samples: [
      "Você pode me ajudar com esta tarefa?",
      "Gosto de ouvir música enquanto estudo.",
      "Onde fica a estação de trem?",
      "O tempo está ótimo hoje.",
      "Estou aprendendo um novo idioma.",
    ],
  },
  {
    code: "ru",
    name: "Russian",
    also: ["Русский", "Russkiy"],
    samples: [
      "Это простой пример предложения.",
      "Москва — столица России.",
      "Где находится железнодорожный вокзал?",
      "Сегодня прекрасная погода.",
      "Я изучаю новый язык.",
    ],
  },
  {
    code: "uk",
    name: "Ukrainian",
    also: ["Українська"],
    samples: [
      "Київ є столицею України.",
      "Це лише невеликий приклад.",
      "Де знаходиться залізничний вокзал?",
      "Сьогодні чудова погода.",
      "Я вивчаю нову мову.",
    ],
  },
  {
    code: "pl",
    name: "Polish",
    also: ["Polski"],
    samples: [
      "To jest tylko prosty przykład.",
      "Lubię czytać książki wieczorem.",
      "Gdzie jest dworzec kolejowy?",
      "Dziś jest bardzo ładna pogoda.",
      "Uczę się nowego języka.",
    ],
  },
  {
    code: "cs",
    name: "Czech",
    also: ["Česky", "Cesky", "Czechia"],
    samples: [
      "To je jen jednoduchý příklad.",
      "Mám rád cestování vlakem.",
      "Kde je nádraží?",
      "Dnes je krásné počasí.",
      "Učím se nový jazyk.",
    ],
  },
  {
    code: "sk",
    name: "Slovak",
    also: ["Slovenčina"],
    samples: [
      "Toto je len jednoduchý príklad.",
      "Rád chodím do hôr cez víkend.",
      "Kde je železničná stanica?",
      "Dnes je krásne počasie.",
      "Učím sa nový jazyk.",
    ],
  },
  {
    code: "sr",
    name: "Serbian",
    also: ["Srpski"],
    samples: [
      "Ово је само једноставан пример.",
      "Волим да пијем кафу ујутру.",
      "Где је железничка станица?",
      "Данас је дивно време.",
      "Учим нови језик.",
    ],
  },
  {
    code: "hr",
    name: "Croatian",
    also: ["Hrvatski"],
    samples: [
      "Ovo je samo jednostavan primjer.",
      "Volim more i duga putovanja.",
      "Gdje je željeznički kolodvor?",
      "Danas je jako lijepo vrijeme.",
      "Učim novi jezik.",
    ],
  },
  {
    code: "bs",
    name: "Bosnian",
    also: ["Bosanski"],
    samples: [
      "Ovo je samo jednostavan primjer.",
      "Volim da šetam pored rijeke.",
      "Gdje je željeznička stanica?",
      "Danas je lijepo vrijeme.",
      "Učim novi jezik.",
    ],
  },
  {
    code: "ro",
    name: "Romanian",
    also: ["Română", "Romana"],
    samples: [
      "Acesta este doar un exemplu simplu.",
      "Îmi place să citesc seara.",
      "Unde este gara?",
      "Astăzi vremea este foarte frumoasă.",
      "Învăț o limbă nouă.",
    ],
  },
  {
    code: "nl",
    name: "Dutch",
    also: ["Nederlands"],
    samples: [
      "Dit is slechts een eenvoudig voorbeeld.",
      "Ik drink 's ochtends graag koffie.",
      "Waar is het treinstation?",
      "Het weer is vandaag erg mooi.",
      "Ik leer een nieuwe taal.",
    ],
  },
  {
    code: "sv",
    name: "Swedish",
    also: ["Svenska"],
    samples: [
      "Det här är bara ett enkelt exempel.",
      "Jag tycker om att läsa på kvällen.",
      "Var ligger tågstationen?",
      "Vädret är väldigt fint idag.",
      "Jag lär mig ett nytt språk.",
    ],
  },
  {
    code: "no",
    name: "Norwegian",
    also: ["Norsk", "Bokmål", "Nynorsk"],
    samples: [
      "Dette er bare et enkelt eksempel.",
      "Jeg liker å gå tur i fjellet.",
      "Hvor er togstasjonen?",
      "Været er veldig bra i dag.",
      "Jeg lærer et nytt språk.",
    ],
  },
  {
    code: "da",
    name: "Danish",
    also: ["Dansk"],
    samples: [
      "Dette er blot et simpelt eksempel.",
      "Jeg kan godt lide at cykle i byen.",
      "Hvor ligger togstationen?",
      "Vejret er rigtig godt i dag.",
      "Jeg lærer et nyt sprog.",
    ],
  },
  {
    code: "fi",
    name: "Finnish",
    also: ["Suomi"],
    samples: [
      "Tämä on vain yksinkertainen esimerkki.",
      "Pidän hiljaisista talvi-illoista.",
      "Missä rautatieasema on?",
      "Tänään on todella kaunis sää.",
      "Opettelen uutta kieltä.",
    ],
  },
  {
    code: "is",
    name: "Icelandic",
    also: ["Íslenska", "Islenska"],
    samples: [
      "Þetta er aðeins einfalt dæmi.",
      "Mér líkar að lesa á kvöldin.",
      "Hvar er lestarstöðin?",
      "Veðrið er mjög gott í dag.",
      "Ég er að læra nýtt tungumál.",
    ],
  },
  {
    code: "et",
    name: "Estonian",
    also: ["Eesti"],
    samples: [
      "See on vaid lihtne näide.",
      "Mulle meeldib jalutada metsas.",
      "Kus asub raudteejaam?",
      "Täna on väga ilus ilm.",
      "Ma õpin uut keelt.",
    ],
  },
  {
    code: "lv",
    name: "Latvian",
    also: ["Latviešu"],
    samples: [
      "Tas ir tikai vienkāršs piemērs.",
      "Man patīk klausīties mūziku.",
      "Kur atrodas dzelzceļa stacija?",
      "Šodien laikapstākļi ir ļoti labi.",
      "Es mācos jaunu valodu.",
    ],
  },
  {
    code: "lt",
    name: "Lithuanian",
    also: ["Lietuvių", "Lietuviu"],
    samples: [
      "Tai tik paprastas pavyzdys.",
      "Man patinka vaikščioti vakare.",
      "Kur yra geležinkelio stotis?",
      "Šiandien oras labai geras.",
      "Aš mokausi naujos kalbos.",
    ],
  },
  {
    code: "el",
    name: "Greek",
    also: ["Ελληνικά", "Hellenic"],
    samples: [
      "Αυτό είναι μόνο ένα απλό παράδειγμα.",
      "Μου αρέσει να διαβάζω το βράδυ.",
      "Πού είναι ο σιδηροδρομικός σταθμός;",
      "Σήμερα ο καιρός είναι πολύ καλός.",
      "Μαθαίνω μια νέα γλώσσα.",
    ],
  },
  {
    code: "tr",
    name: "Turkish",
    also: ["Türkçe", "Turkce"],
    samples: [
      "Bu sadece basit bir örnektir.",
      "Akşamları kitap okumayı seviyorum.",
      "Bugün hava gerçekten çok güzel.",
      "Tren istasyonu nerede?",
      "Yeni bir dil öğreniyorum.",
    ],
  },
  {
    code: "ar",
    name: "Arabic",
    also: ["العربية", "Arab"],
    dir: "rtl",
    samples: [
      "هذا مجرد مثال بسيط.",
      "أحب قراءة الكتب في المساء.",
      "أين تقع محطة القطار؟",
      "الطقس جميل اليوم.",
      "أنا أتعلم لغة جديدة.",
    ],
  },
  {
    code: "he",
    name: "Hebrew",
    also: ["Ivrit", "עברית"],
    dir: "rtl",
    samples: [
      "זה רק דוגמה פשוטה.",
      "אני אוהב לקרוא בערב.",
      "איפה תחנת הרכבת?",
      "מזג האוויר נעים היום.",
      "אני לומד שפה חדשה.",
    ],
  },
  {
    code: "fa",
    name: "Persian",
    also: ["Farsi", "فارسی"],
    dir: "rtl",
    samples: [
      "این فقط یک نمونهٔ ساده است.",
      "من شب‌ها کتاب خواندن را دوست دارم.",
      "ایستگاه قطار کجاست؟",
      "هوا امروز خیلی خوب است.",
      "دارم یک زبان جدید یاد می‌گیرم.",
    ],
  },
  {
    code: "ur",
    name: "Urdu",
    also: ["اردو"],
    dir: "rtl",
    samples: [
      "یہ صرف ایک سادہ مثال ہے۔",
      "مجھے شام کو کتابیں پڑھنا پسند ہے۔",
      "ریلوے اسٹیشن کہاں ہے؟",
      "آج موسم بہت اچھا ہے۔",
      "میں ایک نئی زبان سیکھ رہا ہوں۔",
    ],
  },
  {
    code: "hi",
    name: "Hindi",
    also: ["हिन्दी", "Hindi-Urdu"],
    samples: [
      "यह सिर्फ एक सरल उदाहरण है।",
      "मुझे शाम को किताबें पढ़ना पसंद है।",
      "रेलवे स्टेशन कहाँ है?",
      "आज मौसम बहुत अच्छा है।",
      "मैं एक नई भाषा सीख रहा हूँ।",
    ],
  },
  {
    code: "bn",
    name: "Bengali",
    also: ["Bangla", "বাংলা"],
    samples: [
      "এটি কেবল একটি সাধারণ উদাহরণ।",
      "আমি সন্ধ্যায় বই পড়তে পছন্দ করি।",
      "রেলস্টেশন কোথায়?",
      "আজ আবহাওয়া খুব ভালো।",
      "আমি একটি নতুন ভাষা শিখছি।",
    ],
  },
  {
    code: "ta",
    name: "Tamil",
    also: ["தமிழ்"],
    samples: [
      "இது ஒரு எளிய எடுத்துக்காட்டு மட்டுமே.",
      "எனக்கு மாலையில் படிப்பது பிடிக்கும்.",
      "ரயில் நிலையம் எங்கே இருக்கிறது?",
      "இன்று வானிலை மிகவும் நன்றாக உள்ளது.",
      "நான் ஒரு புதிய மொழி கற்கிறேன்.",
    ],
  },
  {
    code: "te",
    name: "Telugu",
    also: ["తెలుగు"],
    samples: [
      "ఇది ఒక సాధారణ ఉదాహరణ మాత్రమే.",
      "నాకు సాయంత్రం చదవడం ఇష్టం.",
      "రైల్వే స్టేషన్ ఎక్కడ ఉంది?",
      "ఈరోజు వాతావరణం బాగుంది.",
      "నేను కొత్త భాష నేర్చుకుంటున్నాను.",
    ],
  },
  {
    code: "ml",
    name: "Malayalam",
    also: ["മലയാളം"],
    samples: [
      "ഇത് ഒരു ലളിതമായ ഉദാഹരണമാണ്.",
      "എനിക്ക് വൈകുന്നേരങ്ങളിൽ വായിക്കാൻ ഇഷ്ടമാണ്.",
      "ട്രെയിൻ സ്റ്റേഷൻ എവിടെയാണ്?",
      "ഇന്ന് കാലാവസ്ഥ വളരെ നല്ലതാണ്.",
      "ഞാൻ ഒരു പുതിയ ഭാഷ പഠിക്കുന്നു.",
    ],
  },
  {
    code: "kn",
    name: "Kannada",
    also: ["ಕನ್ನಡ"],
    samples: [
      "ಇದು ಒಂದು ಸರಳ ಉದಾಹರಣೆ ಮಾತ್ರ.",
      "ನನಗೆ ಸಂಜೆ ಪುಸ್ತಕ ಓದುವುದು ಇಷ್ಟ.",
      "ರೈಲು ನಿಲ್ದಾಣ ಎಲ್ಲಿದೆ?",
      "ಇಂದು ಹವಾಮಾನ ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ.",
      "ನಾನು ಹೊಸ ಭಾಷೆಯನ್ನು ಕಲಿಯುತ್ತಿದ್ದೇನೆ.",
    ],
  },
  {
    code: "pa",
    name: "Punjabi",
    also: ["ਪੰਜਾਬੀ", "Panjabi"],
    samples: [
      "ਇਹ ਸਿਰਫ਼ ਇੱਕ ਸਧਾਰਣ ਉਦਾਹਰਨ ਹੈ।",
      "ਮੈਨੂੰ ਸ਼ਾਮ ਨੂੰ ਕਿਤਾਬਾਂ ਪੜ੍ਹਨਾ ਪਸੰਦ ਹੈ।",
      "ਰੇਲਵੇ ਸਟੇਸ਼ਨ ਕਿੱਥੇ ਹੈ?",
      "ਅੱਜ ਮੌਸਮ ਬਹੁਤ ਵਧੀਆ ਹੈ।",
      "ਮੈਂ ਇੱਕ ਨਵੀਂ ਭਾਸ਼ਾ ਸਿੱਖ ਰਿਹਾ ਹਾਂ।",
    ],
  },
  {
    code: "gu",
    name: "Gujarati",
    also: ["ગુજરાતી"],
    samples: [
      "આ માત્ર એક સરળ ઉદાહરણ છે.",
      "મને સાંજે પુસ્તકો વાંચવા ગમે છે.",
      "રેલવે સ્ટેશન ક્યાં છે?",
      "આજે હવામાન ખૂબ સારું છે.",
      "હું નવી ભાષા શીખી રહ્યો છું.",
    ],
  },
  {
    code: "zh-Hans",
    name: "Chinese",
    also: [
      "Mandarin",
      "Putonghua",
      "Standard Chinese",
      "中文",
      "简体中文",
      "Chinese (Simplified)",
    ],
    samples: [
      "这只是一个简单的例子。",
      "我喜欢在晚上读书。",
      "今天天气非常好。",
      "火车站在哪里？",
      "我正在学习一门新的语言。",
    ],
  },
  {
    code: "zh-Hant",
    name: "Chinese (Traditional)",
    also: ["繁體中文", "Traditional Chinese"],
    samples: [
      "這只是一個簡單的例子。",
      "我喜歡在晚上讀書。",
      "今天天氣非常好。",
      "火車站在哪裡？",
      "我正在學習一門新的語言。",
    ],
  },
  {
    code: "ja",
    name: "Japanese",
    also: ["日本語", "Nihongo"],
    samples: [
      "これはただの簡単な例です。",
      "私は夜に本を読むのが好きです。",
      "今日はとてもいい天気ですね。",
      "駅はどこにありますか。",
      "新しい言語を勉強しています。",
    ],
  },
  {
    code: "ko",
    name: "Korean",
    also: ["한국어", "Hangul"],
    samples: [
      "이것은 간단한 예일 뿐입니다.",
      "저는 저녁에 책 읽는 것을 좋아해요.",
      "오늘 날씨가 정말 좋네요.",
      "역은 어디에 있나요?",
      "새로운 언어를 배우고 있어요.",
    ],
  },
  {
    code: "vi",
    name: "Vietnamese",
    also: ["Tiếng Việt", "Tieng Viet"],
    samples: [
      "Đây chỉ là một ví dụ đơn giản.",
      "Tôi thích đọc sách vào buổi tối.",
      "Hôm nay thời tiết rất đẹp.",
      "Ga tàu ở đâu vậy?",
      "Tôi đang học một ngôn ngữ mới.",
    ],
  },
  {
    code: "th",
    name: "Thai",
    also: ["ไทย"],
    samples: [
      "นี่เป็นเพียงตัวอย่างง่ายๆ เท่านั้น",
      "ฉันชอบอ่านหนังสือตอนเย็น",
      "วันนี้อากาศดีมากเลย",
      "สถานีรถไฟอยู่ที่ไหน",
      "ฉันกำลังเรียนภาษาใหม่",
    ],
  },
  {
    code: "id",
    name: "Indonesian",
    also: ["Bahasa Indonesia", "Indo"],
    samples: [
      "Ini hanyalah contoh sederhana.",
      "Saya suka membaca buku di malam hari.",
      "Hari ini cuacanya sangat bagus.",
      "Stasiun kereta ada di mana?",
      "Saya sedang belajar bahasa baru.",
    ],
  },
  {
    code: "ms",
    name: "Malay",
    also: ["Bahasa Melayu"],
    samples: [
      "Ini hanya contoh yang ringkas.",
      "Saya suka membaca buku pada waktu malam.",
      "Hari ini cuaca sangat baik.",
      "Stesen kereta api di mana?",
      "Saya sedang belajar bahasa baharu.",
    ],
  },
  {
    code: "tl",
    name: "Filipino",
    also: ["Tagalog"],
    samples: [
      "Isa lamang itong simpleng halimbawa.",
      "Mahilig akong magbasa tuwing gabi.",
      "Ang ganda ng panahon ngayon.",
      "Nasaan ang istasyon ng tren?",
      "Nag-aaral ako ng bagong wika.",
    ],
  },
  {
    code: "sw",
    name: "Swahili",
    also: ["Kiswahili"],
    samples: [
      "Hii ni mfano rahisi tu.",
      "Napenda kusoma vitabu jioni.",
      "Leo hali ya hewa ni nzuri sana.",
      "Kituo cha reli kiko wapi?",
      "Ninajifunza lugha mpya.",
    ],
  },
  {
    code: "am",
    name: "Amharic",
    also: ["አማርኛ"],
    samples: [
      "ይህ ቀላል ምሳሌ ብቻ ነው።",
      "እኔ በማታ መጽሐፍ ማንበብ እወዳለሁ።",
      "ዛሬ የአየር ንብረት ጥሩ ነው።",
      "የባቡር ጣቢያው የት አለ?",
      "አዲስ ቋንቋ እማራለሁ።",
    ],
  },
  {
    code: "jv",
    name: "Javanese",
    also: ["Basa Jawa", "Jawa"],
    samples: [
      "Iki mung tuladha prasaja.",
      "Aku seneng maca ing wayah bengi.",
      "Stasiun sepur ana ing endi?",
      "Dina iki cuacane apik banget.",
      "Aku lagi sinau basa anyar.",
    ],
  },
  {
    code: "su",
    name: "Sundanese",
    also: ["Basa Sunda", "Sunda"],
    samples: [
      "Ieu ngan ukur conto basajan.",
      "Kuring resep maca peuting.",
      "Stasiun karéta aya di mana?",
      "Dinten ieu cuacana saé pisan.",
      "Kuring keur diajar basa anyar.",
    ],
  },
  {
    code: "ceb",
    name: "Cebuano",
    also: ["Bisaya", "Sinugboanon"],
    samples: [
      "Kini usa ra ka yano nga pananglitan.",
      "Ganahan ko mobasa sa gabii.",
      "Asa ang estasyon sa tren?",
      "Nindot kaayo ang panahon karon.",
      "Nagatun-on ko og bag-ong pinulongan.",
    ],
  },
  {
    code: "ig",
    name: "Igbo",
    also: ["Asụsụ Igbo"],
    samples: [
      "Nke a bụ nanị ihe atụ dị mfe.",
      "A na m enwe mmasị ịgụ akwụkwọ n'abalị.",
      "Ebee ka ọdụ ụgbọ oloko dị?",
      "Taa, ihu igwe mara ezigbo mma.",
      "Ana m amụta asụsụ ọhụrụ.",
    ],
  },
  {
    code: "ny",
    name: "Chichewa",
    also: ["Nyanja", "Chewa"],
    samples: [
      "Ichi ndi chitsanzo chophweka chabe.",
      "Ndimasangalala kuwerenga madzulo.",
      "Stesheni ya sitima ili kuti?",
      "Lero nyengo ndi yabwino kwambiri.",
      "Ndikuphunzira chinenero chatsopano.",
    ],
  },
  {
    code: "bho",
    name: "Bhojpuri",
    also: ["भोजपुरी"],
    samples: [
      "ई बस एक साधारण नमूना बा।",
      "हम संझा में किताब पढ़े के पसंद करेली।",
      "रेलवे स्टेशन कहाँ बा?",
      "आज मौसम बहुत बढ़िया बा।",
      "हम नयी भाषा सीखत बानी।",
    ],
  },
  {
    code: "mai",
    name: "Maithili",
    also: ["मैथिली"],
    samples: [
      "ई सिर्फ एक सरल उदाहरण अछि।",
      "हमरा साँझ में किताब पढ़नाइ नीक लगैत अछि।",
      "रेलवे स्टेशन कतय अछि?",
      "आइ मौसम बहुत नीक अछि।",
      "हम नयका भाषा सिखि रहल छी।",
    ],
  },
  {
    code: "be",
    name: "Belarusian",
    also: ["Беларуская"],
    samples: [
      "Гэта толькі просты прыклад.",
      "Мне падабаецца чытаць увечары.",
      "Дзе знаходзіцца чыгуначны вакзал?",
      "Сёння надвор'е вельмі добрае.",
      "Я вучу новую мову.",
    ],
  },
  {
    code: "sl",
    name: "Slovenian",
    also: ["Slovenščina"],
    samples: [
      "To je le preprost primer.",
      "Rad berem zvečer.",
      "Kje je železniška postaja?",
      "Danes je vreme zelo lepo.",
      "Učim se novega jezika.",
    ],
  },
  {
    code: "ca",
    name: "Catalan",
    also: ["Català"],
    samples: [
      "Això és només un exemple senzill.",
      "M'agrada llegir al vespre.",
      "On és l'estació de tren?",
      "Avui fa molt bon temps.",
      "Estic aprenent una llengua nova.",
    ],
  },
  {
    code: "gl",
    name: "Galician",
    also: ["Galego"],
    samples: [
      "Isto é só un exemplo sinxelo.",
      "Gústame ler pola noite.",
      "Onde está a estación de tren?",
      "Hoxe fai moi bo tempo.",
      "Estou aprendendo unha lingua nova.",
    ],
  },
  {
    code: "mt",
    name: "Maltese",
    also: ["Malti"],
    samples: [
      "Dan huwa eżempju sempliċi biss.",
      "Inħobb naqra filgħaxija.",
      "Fejn tinsab l-istazzjon tal-ferrovija?",
      "Illum it-temp sabiħ ħafna.",
      "Qed nitgħallem lingwa ġdida.",
    ],
  },
  {
    code: "gd",
    name: "Scottish Gaelic",
    also: ["Gàidhlig"],
    samples: [
      "Chan eil seo ach eisimpleir sìmplidh.",
      "Is toil leam leughadh feasgar.",
      "Càite bheil stèisean na trèana?",
      "Tha an t-sìde glè mhath an-diugh.",
      "Tha mi ag ionnsachadh cànan ùr.",
    ],
  },
  {
    code: "br",
    name: "Breton",
    also: ["Brezhoneg"],
    samples: [
      "N'eo ket nemet ur skouer eeun.",
      "Plijout a ra din lenn da noz.",
      "E pelec'h emañ ar gare?",
      "Mat-tre eo an amzer hiziv.",
      "Emaon o teskiñ ur yezh nevez.",
    ],
  },
  {
    code: "fy",
    name: "Frisian",
    also: ["Frysk"],
    samples: [
      "Dit is mar in ienfâldich foarbyld.",
      "Ik lês graach jûns.",
      "Wêr is it treinstasjon?",
      "Hjoed is it waar tige moai.",
      "Ik lear in nije taal.",
    ],
  },
  {
    code: "la",
    name: "Latin",
    samples: [
      "Hoc tantum exemplum simplex est.",
      "Vesperi legere amo.",
      "Ubi est statio ferriviaria?",
      "Hodie tempestas valde bona est.",
      "Linguam novam disco.",
    ],
  },
  {
    code: "mi",
    name: "Māori",
    also: ["Te Reo Māori"],
    samples: [
      "He tauira māmā noa iho tēnei.",
      "He pai ki ahau te pānui i te ahiahi.",
      "Kei hea te teihana tereina?",
      "He tino pai te āhua o te rangi i tēnei rā.",
      "Kei te ako ahau i tētahi reo hōu.",
    ],
  },
  {
    code: "sm",
    name: "Samoan",
    samples: [
      "O se fa'ata'ita'iga faigofie lenei.",
      "Ou te fiafia e faitau i le afiafi.",
      "O fea le nofoaga o nofoaafi?",
      "E matagofie tele le tau i le aso.",
      "O lo'o ou a'oa'oina se gagana fou.",
    ],
  },
  {
    code: "mg",
    name: "Malagasy",
    samples: [
      "Ohatra tsotra fotsiny izao.",
      "Tiako ny mamaky boky hariva.",
      "Aiza ny gara?",
      "Tsara be ny toetr'andro anio.",
      "Mianatra fiteny vaovao aho.",
    ],
  },
  {
    code: "ht",
    name: "Haitian Creole",
    also: ["Kreyòl Ayisyen"],
    samples: [
      "Sa a se yon egzanp senp sèlman.",
      "Mwen renmen li nan aswè.",
      "Ki kote estasyon tren an ye?",
      "Jodi a tan an bèl anpil.",
      "M ap aprann yon nouvo lang.",
    ],
  },
  {
    code: "tg",
    name: "Tajik",
    also: ["Тоҷикӣ"],
    samples: [
      "Ин танҳо мисоли оддӣ аст.",
      "Ман бегоҳӣ хонданро дӯст медорам.",
      "Истгоҳи қатор дар куҷост?",
      "Имрӯз ҳаво бисёр хуб аст.",
      "Ман забони нав меомӯзам.",
    ],
  },
  {
    code: "ky",
    name: "Kyrgyz",
    also: ["Кыргызча"],
    samples: [
      "Бул жөнөкөй гана мисал.",
      "Кечинде китеп окуганды жактырам.",
      "Темир жол вокзалы кайда?",
      "Бүгүн аба ырайы абдан жакшы.",
      "Мен жаңы тил үйрөнүп жатам.",
    ],
  },
  {
    code: "tk",
    name: "Turkmen",
    also: ["Türkmençe"],
    samples: [
      "Bu diňe ýönekeý mysal.",
      "Men agşam kitap okamagy halayaryn.",
      "Demir ýol wokzaly nirede?",
      "Şu gün howa gaty gowy.",
      "Men täze dil öwrenýärin.",
    ],
  },
  {
    code: "si",
    name: "Sinhala",
    also: ["සිංහල"],
    samples: [
      "මෙය සරල උදාහරණයක් පමණි.",
      "මට සන්ධ්‍යා වේලා පොත් කියවීමට කැමතියි.",
      "දුම්රිය ස්ථානය කොහෙද?",
      "අද කාලගුණය ඉතා හොඳයි.",
      "මම නව භාෂාවක් ඉගෙන ගන්නෙමි.",
    ],
  },
  {
    code: "lo",
    name: "Lao",
    also: ["ລາວ"],
    samples: [
      "ນີ້ແມ່ນຕົວຢ່າງງ່າຍໆເທົ່ານັ້ນ.",
      "ຂ້ອຍມັກອ່ານປຶ້ມໃນຕອນແລງ.",
      "ສະຖານີລົດໄຟຢູ່ໃສ?",
      "ມື້ນີ້ອາກາດດີຫຼາຍ.",
      "ຂ້ອຍກຳລັງຮຽນພາສາໃໝ່.",
    ],
  },
  {
    code: "km",
    name: "Khmer",
    also: ["ភាសាខ្មែរ"],
    samples: [
      "នេះគ្រាន់តែជាឧទាហរណ៍សាមញ្ញប៉ុណ្ណោះ។",
      "ខ្ញុំចូលចិត្តអានសៀវភៅពេលល្ងាច។",
      "ស្ថានីយ៍រថភ្លើងស្ថិតនៅទីណា?",
      "ថ្ងៃនេះអាកាសធាតុល្អណាស់។",
      "ខ្ញុំកំពុងរៀនភាសាថ្មី។",
    ],
  },
  {
    code: "my",
    name: "Burmese",
    also: ["မြန်မာ"],
    samples: [
      "ဒါ ရိုးရှင်းတဲ့ နမူနာ တစ်ခုပါ။",
      "ညဘက် စာဖတ်ရတာ ကြိုက်တယ်။",
      "ရထားဘူတာ ဘယ်မှာလဲ?",
      "ဒီနေ့ ရာသီဥတု ကောင်းပါတယ်။",
      "ဘာသာစကား အသစ် လေ့လာနေပါတယ်။",
    ],
  },
  {
    code: "mn",
    name: "Mongolian",
    also: ["Монгол"],
    samples: [
      "Энэ бол зүгээр л энгийн жишээ.",
      "Би орой ном унших дуртай.",
      "Галт тэрэгний буудал хаана байна вэ?",
      "Өнөөдөр цаг агаар маш сайхан байна.",
      "Би шинэ хэл сурч байна.",
    ],
  },
  {
    code: "mr",
    name: "Marathi",
    also: ["मराठी"],
    samples: [
      "हे फक्त एक साधे उदाहरण आहे.",
      "मला संध्याकाळी वाचन करायला आवडते.",
      "रेल्वे स्टेशन कुठे आहे?",
      "आज हवा खूप छान आहे.",
      "मी एक नवी भाषा शिकत आहे.",
    ],
  },
  {
    code: "as",
    name: "Assamese",
    also: ["অসমীয়া"],
    samples: [
      "এইটো কেৱল এটা সাধাৰণ উদাহৰণ।",
      "মোৰ সন্ধিয়াত পঢ়িবলৈ ভাল লাগে।",
      "ৰেলৱে ষ্টেচন ক'ত আছে?",
      "আজি বতৰৰ অৱস্থা অত্যন্ত ভাল।",
      "মই এটা নতুন ভাষা শিকি আছোঁ।",
    ],
  },
  {
    code: "or",
    name: "Odia",
    also: ["ଓଡ଼ିଆ"],
    samples: [
      "ଏହା କେବଳ ଏକ ସରଳ ଉଦାହରଣ।",
      "ମୁଁ ସନ୍ଧ୍ୟାରେ ପଢ଼ିବାକୁ ଭଲ ପାଏ।",
      "ରେଳ ବସ-ଷ୍ଟେସନ୍ କେଉଁଠି ଅଛି?",
      "ଆଜି ଆବହାଓ ଖୁବ ଭଲ ଅଛି।",
      "ମୁଁ ଏକ ନୂଆ ଭାଷା ଶିଖୁଛି।",
    ],
  },
  {
    code: "sd",
    name: "Sindhi",
    also: ["سنڌي"],
    dir: "rtl",
    samples: [
      "هي رڳو هڪ سادو مثال آهي.",
      "مون کي شام جو ڪتاب پڙهڻ پسند آهي.",
      "ريلوے اسٽيشن ڪٿي آهي؟",
      "اڄ موسم ڏاڍو سٺو آهي.",
      "مان هڪ نئين ٻولي سکي رهيو آهيان.",
    ],
  },
  {
    code: "zu",
    name: "Zulu",
    also: ["isiZulu"],
    samples: [
      "Lokhu isibonelo esilula nje.",
      "Ngithanda ukufunda kusihlwa.",
      "Isiteshi sesitimela sikuphi?",
      "Namuhla isimo sezulu sihle kakhulu.",
      "Ngifunda ulimi olusha.",
    ],
  },
  {
    code: "xh",
    name: "Xhosa",
    also: ["isiXhosa"],
    samples: [
      "Lo ngumzekelo olula nje.",
      "Ndithanda ukufunda ngokuhlwa.",
      "Isikhululo sikaloliwe sikuphi?",
      "Namhlanje imozulu intle kakhulu.",
      "Ndifunda ulwimi olutsha.",
    ],
  },
  {
    code: "sn",
    name: "Shona",
    samples: [
      "Ichi muenzaniso wakapfava chete.",
      "Ndinofarira kuverenga manheru.",
      "Chiteshi chechitima chiripi?",
      "Nhasi mamiriro ekunze akanaka zvikuru.",
      "Ndiri kudzidza mutauro mutsva.",
    ],
  },

  {
    code: "af",
    name: "Afrikaans",
    samples: [
      "Dit is net 'n eenvoudige voorbeeld.",
      "Ek hou daarvan om saans te lees.",
      "Waar is die treinstasie?",
      "Die weer is vandag baie mooi.",
      "Ek leer 'n nuwe taal.",
    ],
  },
  {
    code: "sq",
    name: "Albanian",
    also: ["Shqip"],
    samples: [
      "Kjo është vetëm një shembull i thjeshtë.",
      "Më pëlqen të lexoj në mbrëmje.",
      "Ku ndodhet stacioni i trenit?",
      "Moti sot është shumë i mirë.",
      "Po mësoj një gjuhë të re.",
    ],
  },
  {
    code: "hy",
    name: "Armenian",
    also: ["Հայերեն", "Hayeren"],
    samples: [
      "Սա պարզապես պարզ օրինակ է։",
      "Ես սիրում եմ երեկոյան կարդալ։",
      "Որտեղ է երկաթուղային կայարանը՞:",
      "Այսօր եղանակը շատ գեղեցիկ է։",
      "Ես սովորում եմ նոր լեզու։",
    ],
  },
  {
    code: "az",
    name: "Azerbaijani",
    also: ["Azeri", "Azərbaycan dili"],
    samples: [
      "Bu sadəcə sadə bir nümunədir.",
      "Axşamlar kitab oxumağı sevirəm.",
      "Qatar stansiyası haradadır?",
      "Bu gün hava çox gözəldir.",
      "Mən yeni bir dil öyrənirəm.",
    ],
  },
  {
    code: "eu",
    name: "Basque",
    also: ["Euskara"],
    samples: [
      "Hau adibide sinple bat besterik ez da.",
      "Arratsaldeetan irakurtzea gustatzen zait.",
      "Non dago tren geltokia?",
      "Gaur eguraldia oso ona da.",
      "Hizkuntza berri bat ikasten ari naiz.",
    ],
  },
  {
    code: "bg",
    name: "Bulgarian",
    also: ["Български", "Balgarski"],
    samples: [
      "Това е просто пример.",
      "Обичам да чета вечер.",
      "Къде е железопътната гара?",
      "Днес времето е много хубаво.",
      "Уча нов език.",
    ],
  },
  {
    code: "hu",
    name: "Hungarian",
    also: ["Magyar"],
    samples: [
      "Ez csak egy egyszerű példa.",
      "Szeretek esténként olvasni.",
      "Hol van a vasútállomás?",
      "Ma nagyon szép az idő.",
      "Új nyelvet tanulok.",
    ],
  },
  {
    code: "ga",
    name: "Irish",
    also: ["Gaeilge", "Irish Gaelic"],
    samples: [
      "Níl anseo ach sampla simplí.",
      "Is maith liom léamh tráthnóna.",
      "Cá bhfuil stáisiún na traenach?",
      "Tá an aimsir an-deas inniu.",
      "Tá mé ag foghlaim teanga nua.",
    ],
  },
  {
    code: "cy",
    name: "Welsh",
    also: ["Cymraeg"],
    samples: [
      "Dim ond enghraifft syml yw hon.",
      "Rwy'n hoffi darllen gyda'r nos.",
      "Ble mae'r orsaf drenau?",
      "Mae'r tywydd yn braf heddiw.",
      "Rwy'n dysgu iaith newydd.",
    ],
  },
  {
    code: "eo",
    name: "Esperanto",
    samples: [
      "Ĉi tio estas nur simpla ekzemplo.",
      "Mi ŝatas legi vespere.",
      "Kie estas la fervoja stacidomo?",
      "Hodiaŭ la vetero estas tre bela.",
      "Mi lernas novan lingvon.",
    ],
  },
  {
    code: "mk",
    name: "Macedonian",
    also: ["Македонски"],
    samples: [
      "Ова е само едноставен пример.",
      "Сакам да читам навечер.",
      "Каде е железничката станица?",
      "Денес времето е многу убаво.",
      "Учам нов јазик.",
    ],
  },
  {
    code: "ka",
    name: "Georgian",
    also: ["ქართული"],
    samples: [
      "ეს უბრალოდ მარტივი მაგალითია.",
      "საღამოობით კითხვა მიყვარს.",
      "სად არის მატარებლის სადგური?",
      "დღეს ამინდი ძალიან კარგია.",
      "მე ვსწავლობ ახალ ენას.",
    ],
  },
  {
    code: "ku-Latn",
    name: "Kurdish (Kurmanji)",
    also: ["Kurdish", "Kurmanji", "Kurmancî"],
    samples: [
      "Ev tenê mînakê hêsan e.",
      "Ez êvaran xwendinê hez dikim.",
      "Stasyona trenê li ku ye?",
      "Îro hewa gelek baş e.",
      "Ez zimanek nû fêrinim.",
    ],
  },
  {
    code: "ckb",
    name: "Kurdish (Sorani)",
    also: ["Kurdî (Soranî)", "کوردیی ناوەندی"],
    dir: "rtl",
    samples: [
      "ئەمە تەنها نموونەیەکی سادەیە.",
      "من حەزم بە خوێندنەوەی ئێواران.",
      "وەستگەی شەمەندەفەر لە کوێیە؟",
      "ئەمڕۆ کەشۆهەوا زۆر باشە.",
      "من زمانێکی نوێ فێردەبەم.",
    ],
  },
  {
    code: "ps",
    name: "Pashto",
    also: ["پښتو", "Pakhto", "Pashtu"],
    dir: "rtl",
    samples: [
      "دا یوازې یو ساده مثال دی.",
      "زه ماښامونه لوستل خوښوم.",
      "د اورګاډي اډه چیرته ده؟",
      "نن هوا ډېره ښه ده.",
      "زه یوه نوې ژبه زده کوم.",
    ],
  },
  {
    code: "yi",
    name: "Yiddish",
    also: ["ייִדיש", "Idish"],
    dir: "rtl",
    samples: [
      "דאָס איז נאָר אַ פּשוט בייַשפּיל.",
      "איך האָב ליב צו לייענען אין אָוונט.",
      "וווּ איז די באַן סטאַנציע?",
      "הײַנט איז די וועטער זייער שיין.",
      "איך לערן אַ נײַע שפּראַך.",
    ],
  },
  {
    code: "so",
    name: "Somali",
    also: ["Af-Soomaali"],
    samples: [
      "Tani waa tusaale fudud oo keliya.",
      "Waxaan jeclahay akhriska fiidkii.",
      "Saldhigga tareenka xaggee ku yaal?",
      "Maanta cimiladu aad bay u wanaagsan tahay.",
      "Waxaan baranayaa luqad cusub.",
    ],
  },
  {
    code: "yo",
    name: "Yoruba",
    samples: [
      "Eyi jẹ́ àpẹẹrẹ ìròrùn kan péré.",
      "Mo fẹ́ràn kíkà ní alẹ́.",
      "Ibùdó ọkọ oju irin wà níbo?",
      "Òní ojú-ọjọ́ dára gan-an.",
      "Mo ń kọ́ èdè tuntun kan.",
    ],
  },
  {
    code: "ha",
    name: "Hausa",
    samples: [
      "Wannan misali ne mai sauƙi kawai.",
      "Ina son karatu da yamma.",
      "Ina tashar jirgin ƙasa take?",
      "Yau yanayi yana da kyau sosai.",
      "Ina koyo sabon yare.",
    ],
  },
  {
    code: "ne",
    name: "Nepali",
    also: ["नेपाली"],
    samples: [
      "यो केवल एउटा साधारण उदाहरण हो।",
      "म साँझमा पढ्न मन पराउँछु।",
      "रेलवे स्टेशन कहाँ छ?",
      "आज मौसम धेरै राम्रो छ।",
      "म नयाँ भाषा सिक्दैछु।",
    ],
  },
  {
    code: "uz",
    name: "Uzbek",
    also: ["Oʻzbek"],
    samples: [
      "Bu faqat oddiy misol.",
      "Kechqurun kitob o‘qishni yoqtiraman.",
      "Temir yo‘l vokzali qayerda?",
      "Bugun ob-havo juda yaxshi.",
      "Men yangi til o‘rganayapman.",
    ],
  },
  {
    code: "kk",
    name: "Kazakh",
    also: ["Қазақ тілі"],
    samples: [
      "Бұл тек қарапайым мысал.",
      "Маған кешке кітап оқу ұнайды.",
      "Теміржол вокзалы қайда?",
      "Бүгін ауа райы өте жақсы.",
      "Мен жаңа тілді үйреніп жүрмін.",
    ],
  },
];

export const LANGUAGE_SUGGESTIONS: string[] = Array.from(
  new Set(LANGUAGES.flatMap((l) => [l.name, ...(l.also ?? [])])),
).sort((a, b) => a.localeCompare(b));
