name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test -- --reporter=dot
      # playwright optional later:
      # - run: pnpm dlx playwright install --with-deps
      # - run: pnpm e2e
      - run: pnpm build
