// lib/crossword/wordlist.ts
export type Entry = { answer: string; clue: string };

export const WORDS: Entry[] = [
  { answer: "AREA", clue: "Two-dimensional measure" },
  { answer: "ORBIT", clue: "Path around a star" },
  { answer: "ATOM", clue: "Basic unit of matter" },
  { answer: "ARRAY", clue: "Data structure of elements" },
  { answer: "REACT", clue: "Popular front-end library" },
  { answer: "STATE", clue: "Condition or mode" },
  { answer: "DELTA", clue: "Letter after gamma" },
  { answer: "RIVER", clue: "Natural watercourse" },
  { answer: "PARIS", clue: "City on the Seine" },
  { answer: "BERLIN", clue: "Brandenburg Gate city" },
  { answer: "LONDON", clue: "City with the Thames" },
  { answer: "PYTHON", clue: "Language with indentation" },
  { answer: "SCRIPT", clue: "Text for a play" },
  { answer: "EDITOR", clue: "One who revises text" },
  { answer: "PUZZLE", clue: "Something to solve" },
  { answer: "CLUE", clue: "Hint for a solver" },
  { answer: "NODE", clue: "Graph vertex" },
  { answer: "EDGE", clue: "Graph connection" },
  { answer: "ALGORITHM", clue: "Step-by-step procedure" },
  { answer: "GRADIENT", clue: "Slope in math or color" },
  { answer: "NETWORK", clue: "Connected system" },
  { answer: "COMPILER", clue: "Translator for source code" },
  { answer: "BROWSER", clue: "Software to view the web" },
  { answer: "ENGINEER", clue: "Problem solver by trade" },
  { answer: "ROUTER", clue: "Network traffic director" },
  { answer: "ARRAYS", clue: "Multiple linear containers" },
  { answer: "LIST", clue: "Linear collection" },
  { answer: "QUEUE", clue: "FIFO structure" },
  { answer: "STACK", clue: "LIFO structure" },
  { answer: "INPUT", clue: "What you type" },
  { answer: "OUTPUT", clue: "What you get" },
  { answer: "METRIC", clue: "Standard of measurement" },
  { answer: "SUDOKU", clue: "Number-placement puzzle" },
  { answer: "CROSSWORD", clue: "Black-and-white word puzzle" },
  { answer: "ASYNC", clue: "Not happening at once" },
  { answer: "KERNEL", clue: "Core of an OS" },
  { answer: "SERVER", clue: "Provides resources on a network" },
  { answer: "CLIENT", clue: "Consumer on a network" },
  { answer: "VECTOR", clue: "Quantity with magnitude and direction" },
  { answer: "MATRIX", clue: "Rectangular array in math" },
  { answer: "REWRITE", clue: "Do over in new words" },
  { answer: "THEME", clue: "Unifying idea" },
  { answer: "LETTER", clue: "Alphabet member" },
  { answer: "NUMBER", clue: "Mathematical value" },
  { answer: "LATENCY", clue: "Delay on a network" },
  { answer: "BANDWIDTH", clue: "Capacity of a link" },
  { answer: "FRONTEND", clue: "UI side of a stack" },
  { answer: "BACKEND", clue: "Server side of a stack" },
  { answer: "DART", clue: "Language used with Flutter" },
  { answer: "FLUTTER", clue: "UI toolkit by Google" },
  { answer: "RECHARGE", clue: "Fill the battery again" },
  { answer: "SOLDER", clue: "Join with molten metal" },
  { answer: "PARSER", clue: "Component that builds ASTs" },
  { answer: "CACHE", clue: "Speedy memory" },
  { answer: "COOKIE", clue: "Small web token" },
  { answer: "SESSION", clue: "Period of activity" },
  { answer: "STORAGE", clue: "Place for keeping data" },
  { answer: "MOBILE", clue: "Designed for phones" },
  { answer: "DESKTOP", clue: "Designed for PCs" },
  { answer: "BIT", clue: "Binary digit" },
  { answer: "BYTE", clue: "Eight bits" },
  { answer: "EMAIL", clue: "Electronic message" },
  { answer: "LOGIN", clue: "Start a session" },
  { answer: "TOKEN", clue: "Access credential" },
  { answer: "SECRET", clue: "Keep it hidden" },
  { answer: "SECURE", clue: "Safe from threats" },
];
